from .coach_employ import CoachEmployResource
from .coach import CoachResource
from .country import CountryResource
from .game_event import GameEventResource
from .game_penalty import GamePenaltyResource
from .game_player import GamePlayerResource
from .game_team import GameTeamResource
from .game import GameResource
from .index import IndexResource
from .league import LeagueResource
from .player_transfer import PlayerTransferResource
from .player import PlayerResource
from .referee import RefereeResource
from .season import SeasonResource
from .team import TeamResource
from .venue import VenueResource
