from .coach_employ import CoachEmployResource
from .coach import CoachResource
from .country import CountryResource
from .game_event import GameEventResource
from .game import GameResource
from .index import IndexResource
from .league import LeagueResource
from .player import PlayerResource
from .referee import RefereeResource
from .season import SeasonResource
from .team import TeamResource
from .venue import VenueResource
