"""create venue, player, coach & referee models

Revision ID: 2233c41a5d12
Revises: 6bfc112329e3
Create Date: 2024-04-10 20:59:48.767913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2233c41a5d12'
down_revision = '6bfc112329e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coaches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('postion', sa.String(length=50), nullable=False),
    sa.Column('injury', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('games_won')
    op.drop_table('games_drew')
    op.drop_table('games_played')
    op.drop_table('games_loss')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referee_id', sa.UUID(), nullable=False))
        batch_op.drop_constraint('games_home_team_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('games_away_team_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('games_season_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('games_league_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'referees', ['referee_id'], ['id'])
        batch_op.drop_column('game_date_time')
        batch_op.drop_column('season_id')
        batch_op.drop_column('away_team_id')
        batch_op.drop_column('league_id')
        batch_op.drop_column('home_team_id')

    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_constraint('seasons_league_id_fkey', type_='foreignkey')
        batch_op.drop_column('league_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league_id', sa.UUID(), server_default=sa.text("'7df22bfd-ae2d-438b-8e21-cdaabcf5bcff'::uuid"), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('seasons_league_id_fkey', 'leagues', ['league_id'], ['id'])

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_team_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('league_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('away_team_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('season_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('game_date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('games_league_id_fkey', 'leagues', ['league_id'], ['id'])
        batch_op.create_foreign_key('games_season_id_fkey', 'seasons', ['season_id'], ['id'])
        batch_op.create_foreign_key('games_away_team_id_fkey', 'teams', ['away_team_id'], ['id'])
        batch_op.create_foreign_key('games_home_team_id_fkey', 'teams', ['home_team_id'], ['id'])
        batch_op.drop_column('referee_id')

    op.create_table('games_loss',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('game_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name='games_loss_game_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='games_loss_pkey')
    )
    op.create_table('games_played',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('game_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name='games_played_game_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='games_played_pkey')
    )
    op.create_table('games_drew',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('game_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name='games_drew_game_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='games_drew_pkey')
    )
    op.create_table('games_won',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('game_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name='games_won_game_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='games_won_pkey')
    )
    op.drop_table('players')
    op.drop_table('coaches')
    op.drop_table('referees')
    # ### end Alembic commands ###
