"""char len

Revision ID: 331641ba6c7e
Revises: 2233c41a5d12
Create Date: 2024-04-10 21:09:56.758993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '331641ba6c7e'
down_revision = '2233c41a5d12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
