"""create game events, game player,game team table

Revision ID: 344c25b3ba87
Revises: 7ea4641e41a6
Create Date: 2024-04-13 20:24:20.534360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '344c25b3ba87'
down_revision = '7ea4641e41a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'leagues', ['league_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('league_id')

    # ### end Alembic commands ###
