"""feat: added game week column to game model

Revision ID: 4f4b04f70049
Revises: bfc0a8f75782
Create Date: 2024-05-08 16:14:52.044880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4b04f70049'
down_revision = 'bfc0a8f75782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_week', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('game_week')

    # ### end Alembic commands ###
