"""feat: included abbr column to league table

Revision ID: 6727c7277cbc
Revises: 0a5a0d400c3f
Create Date: 2024-03-30 15:12:11.766378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6727c7277cbc'
down_revision = '0a5a0d400c3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abbr', sa.String(
            length=50), nullable=False, server_default='None'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_column('abbr')

    # ### end Alembic commands ###
