"""fix: updated column name of current to current_season

Revision ID: 6bbf2cc23a3b
Revises: 6455f4b8c5c5
Create Date: 2024-03-30 17:25:04.761692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bbf2cc23a3b'
down_revision = '6455f4b8c5c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'current_season', sa.Boolean(), nullable=False, server_default="False"))
        batch_op.drop_column('current')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current', sa.BOOLEAN(),
                            autoincrement=False, nullable=False))
        batch_op.drop_column('current_season')

    # ### end Alembic commands ###
