"""update

Revision ID: 6bfc112329e3
Revises: 6bbf2cc23a3b
Create Date: 2024-04-06 22:51:19.391279

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6bfc112329e3"
down_revision = "6bbf2cc23a3b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("seasons", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "league_id",
                sa.UUID(),
                nullable=False,
                server_default="7df22bfd-ae2d-438b-8e21-cdaabcf5bcff",
            )
        )
        batch_op.create_foreign_key(None, "leagues", ["league_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("seasons", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("league_id")

    # ### end Alembic commands ###
