"""created models for game event, game player & game team

Revision ID: 7ea4641e41a6
Revises: ce78d7bd3f52
Create Date: 2024-04-12 04:55:58.726312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea4641e41a6'
down_revision = 'ce78d7bd3f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_time', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('game_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('weather', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('league_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('season_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('venue_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'venues', ['venue_id'], ['id'])
        batch_op.create_foreign_key(None, 'leagues', ['league_id'], ['id'])
        batch_op.create_foreign_key(None, 'seasons', ['season_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('venue_id')
        batch_op.drop_column('season_id')
        batch_op.drop_column('league_id')
        batch_op.drop_column('weather')
        batch_op.drop_column('game_date')
        batch_op.drop_column('game_time')

    # ### end Alembic commands ###
