"""removal of league id as foreign key in referees

Revision ID: aed5af862616
Revises: 344c25b3ba87
Create Date: 2024-04-13 20:38:52.668977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed5af862616'
down_revision = '344c25b3ba87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('starting_lineup', sa.Boolean(), nullable=False),
    sa.Column('substitute', sa.Boolean(), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('game_team_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['game_team_id'], ['game_teams.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Boolean(), nullable=False),
    sa.Column('event_time', sa.Integer(), nullable=False),
    sa.Column('game_half', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('game_player_id', sa.UUID(), nullable=False),
    sa.Column('game_team_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['game_player_id'], ['game_players.id'], ),
    sa.ForeignKeyConstraint(['game_team_id'], ['game_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('referees', schema=None) as batch_op:
        batch_op.drop_constraint('referees_league_id_fkey', type_='foreignkey')
        batch_op.drop_column('league_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('referees_league_id_fkey', 'leagues', ['league_id'], ['id'])

    op.drop_table('game_events')
    op.drop_table('game_players')
    op.drop_table('game_teams')
    # ### end Alembic commands ###
