"""feat: add footed column to player

Revision ID: bfc0a8f75782
Revises: e44e891cf89b
Create Date: 2024-05-07 07:43:10.013365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfc0a8f75782'
down_revision = 'e44e891cf89b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('footed', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('footed')

    # ### end Alembic commands ###
