"""is goal datatype in game penalty

Revision ID: c3e3a396e640
Revises: 77d8f5cb5622
Create Date: 2024-05-06 09:02:39.736387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e3a396e640'
down_revision = '77d8f5cb5622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_penalties', schema=None) as batch_op:
        batch_op.alter_column('is_goal',
                              existing_type=sa.INTEGER(),
                              type_=sa.Boolean(),
                              existing_nullable=False,
                              postgresql_using='is_goal::boolean')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_penalties', schema=None) as batch_op:
        batch_op.alter_column('is_goal',
                              existing_type=sa.Boolean(),
                              type_=sa.INTEGER(),
                              existing_nullable=False)

    # ### end Alembic commands ###
