"""initialisation

Revision ID: cc223be30252
Revises: 
Create Date: 2023-05-14 13:21:31.133995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc223be30252'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('a_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('a_sessions')
    # ### end Alembic commands ###
