"""#initialisation

Revision ID: dca3192f0d62
Revises: 
Create Date: 2023-03-07 16:53:41.464645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dca3192f0d62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=300), nullable=True),
    sa.Column('last_name', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=70), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('street_name', sa.String(length=50), nullable=True),
    sa.Column('zipcode', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
