"""fix: removed country id in season model

Revision ID: e44e891cf89b
Revises: 24cdfb412cf8
Create Date: 2024-05-07 00:30:58.088087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e44e891cf89b'
down_revision = '24cdfb412cf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_constraint('seasons_country_id_fkey', type_='foreignkey')
        batch_op.drop_column('country_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('seasons_country_id_fkey', 'countries', ['country_id'], ['id'])

    # ### end Alembic commands ###
