"""feat: added retired column to players

Revision ID: edd24aff5b81
Revises: 8e635ca6f827
Create Date: 2024-07-20 08:15:56.361701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edd24aff5b81'
down_revision = '8e635ca6f827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retired', sa.Boolean(),
                            nullable=False, server_default="False"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('retired')

    # ### end Alembic commands ###
