"""updated datatype in game event

Revision ID: efc75744f1b6
Revises: aa3f9b1d08ac
Create Date: 2024-05-05 18:12:53.309264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc75744f1b6'
down_revision = 'aa3f9b1d08ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_events', schema=None) as batch_op:
        batch_op.alter_column('event_type',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_events', schema=None) as batch_op:
        batch_op.alter_column('event_type',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    # ### end Alembic commands ###
